# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: MPL-2.0
---
#photon does not have backward compatibility for legacy distro behavior for sysctl.conf by default
#as it uses systemd-sysctl. set this var so we can use for sysctl conf file value.
sysctl_conf_file: "{{ '/etc/sysctl.d/99-sysctl.conf' if ansible_os_family == 'VMware Photon OS' else '/etc/sysctl.conf' }}"

carvel_tools: "/tmp/carvel-tools"