# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: MPL-2.0
- name: Disable password expiry
  ansible.builtin.shell: sed -i 's/^PASS_MAX_DAYS.*$/PASS_MAX_DAYS -1/g' /etc/login.defs
  args:
    executable: /bin/bash
