---
- name: Modify /bin/sh to point to bash instead of dash
  shell: "{{ item }}"
  with_items:
    - echo "dash dash/sh boolean false" |  debconf-set-selections
    - DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash
