---
- name: Install rpm-build package
  command: tdnf install rpm-build -y

- name: Create rpm build directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "/tmp/va_rpm"
    - "/tmp/va_rpm/BUILD"
    - "/tmp/va_rpm/RPMS"
    - "/tmp/va_rpm/SOURCES"
    - "/tmp/va_rpm/SOURCES/vasecurity"
    - "/tmp/va_rpm/SPECS"
    - "/tmp/va_rpm/INSTALL"

- name: Download va_hardening tar
  unarchive:
    src: "{{ photon_va_hardening_url }}"
    dest: /tmp/va_rpm/SOURCES/vasecurity
    copy: no
    mode: 0755
  retries: 5
  delay: 3

- name: Copy va_hardening files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    mode: 0755
  loop:
    - { src: 'files/va_hardening/OverriddenPDIs', dst: '/tmp/va_rpm/SOURCES/vasecurity/vahardening' }
    - { src: 'files/va_hardening/vasecurity.spec', dst: '/tmp/va_rpm' }

- name: Build va_hardening RPM
  shell: "rpmbuild --buildroot INSTALL --define='_topdir /tmp/va_rpm' --define 'version {{ va_hardening_rpm_version }} ' --define 'release {{ va_hardening_rpm_release }}' --target noarch -bb vasecurity.spec"
  args:
    chdir: "/tmp/va_rpm"

- name: Install va_hardening RPM
  command: "rpm -ihv photon_vasecurity-{{ va_hardening_rpm_version }}-{{ va_hardening_rpm_release }}.noarch.rpm"
  args:
    chdir: "/tmp/va_rpm/RPMS/noarch"

- name: Remove va_hardening build dir
  file:
    state: absent
    path: "/tmp/va_rpm"

- name: Remove rpm-build package
  command: tdnf remove rpm-build -y
